# Generated by Django 5.0.6 on 2026-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon',
            field=models.CharField(blank=True, help_text='إيموجي أو رمز للكارت', max_length=8),
        ),
        migrations.AddField(
            model_name='section',
            name='link_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='section',
            name='link_url',
            field=models.CharField(blank=True, help_text='رابط زر اختياري', max_length=300),
        ),
    ]
